$(document).ready(function() {
  // LIBRARIES CODE
  LibVars = {};
  // PROJECT CODE
  var _that = this;
  $('[obj-name="MainScreen"]').show().triggerHandler('show');
  history.pushState({
    'view': 'MainScreen'
  }, 'MainScreen', '?MainScreen');
});
// Generated by snapp
// 656042-187837-69688-423497
